[tool.poetry]
name = "quack"
description = "Some tooling for SQL/DuckDB"
version = "0.1.0"
authors = []

[tool.poetry.dependencies]
python = "^3.12"
sqlglot = "^26.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
